# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

#baidu_tongji: true

# friends link
links:
  - name: github
    url: https://github.com/
  - name: zhihu
    url: https://www.zhihu.com/
  - name: bilibili
    url: http://www.bilibili.com/
#  - name: email
#    url: ay180629@outlook.com

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
#  - name: About
#    slug: about
#    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/zj2626
- slug: twitter
  url: https://twitter.com/kevinsfork
- slug: rss
	url: /atom.xml
